name: Mon premier workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Affiché un message
        run: echo "Bonjour, je suis un workflow qui affiche un message"
        