name: Commit Message

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  show-commit-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Afficher le message du commit
        run: echo "$(git log -1 --pretty=%B)"
