name: Commit Message

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du repository
        uses: actions/checkout@v4

      - name: Afficher le dernier message de commit
        run: echo "Le dernier commit message est $(git log -1 --pretty=%s)"