name: Tools installer

on: 
  push: 
    branches:
      - main

jobs:
  toolsInstaller:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du repository
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          
      - name: Installer python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: afficher la version de node et python
        run: |
          echo "Node.js version: ${{ steps.node-version.outputs.node-version }}"
          echo "Python version: ${{ steps.python-version.outputs.python-version }}"
